kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Docker Build
  commands:
  - docker login git.roastedcode.com -u lucianciolacdev@gmail.com -p zcn.jwq8fma3FGN6wdx
  - docker build -t git.roastedcode.com/luycki/testapp:staging .

- name: Docker Push
  commands:
  - docker tag testapp:staging
  - docker push git.roastedcode.com/luycki/testapp:staging