kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Docker Build
  environment:
    REGISTRY_USERNAME:
      from_secret: REGISTRY_USERNAME
    REGISTRY_PASSWORD:
      from_secret: REGISTRY_PASSWORD
  commands:
  - docker login git.roastedcode.com -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
  - docker build -t git.roastedcode.com/luycki/testapp:staging .
  - echo $DRONE_BRANCH

- name: Docker Push
  commands:
  # - docker tag testapp:staging git.roastedcode.com/luycki/testapp:staging
  - docker push git.roastedcode.com/luycki/testapp:staging